### ISSUE TITLE
I can use this github repository for personnal project ?

### ISSUE THREAD

**Issue by zuygui** [AykutSarac/epic-games-clone#1]
I can use this github repository for personnal project ?

**Comment by AykutSarac** [comment]
You can use the repository as long as you follow the [MIT License](https://github.com/AykutSarac/epic-games-clone/blob/main/LICENSE).

**Comment by zuygui** [comment]
But I must mentionning you ?

**Comment by AykutSarac** [comment]
> But I must mentionning you ?

If you fork it, no.

**Comment by zuygui** [comment]
Ok, thanks but I don't use finnaly this project
